export const MAIN_MENU = 'MAIN_MENU'
export const QUIZ_SELECTION = 'QUIZ_SELECTION'
export const MODE_SELECTION = 'MODE_SELECTION'
export const IN_GAME = 'IN_GAME'
export const GAME_OVER = 'GAME_OVER'
